version: 0.2

phases:
  install:
    commands:
      - cd client
      - npm ci

  build:
    commands:
      - npm run build

artifacts:
  base-directory: client/dist
  files:
    - '**/*'

cache:
  paths:
    - client/node_modules/**/*
